import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import Icon from '../ui/Icon'
import { useAppStore } from '../../store/useAppStore'
import { INTENTS, INTENT_ICONS, ALL_TOOLS, TRUST_ITEMS } from '../../constants/tools'

export default function HomeView() {
  const { activeIntent, setActiveIntent } = useAppStore()
  const [openFaq, setOpenFaq] = useState(null)

  const displayedTools = activeIntent === 'All'
    ? ALL_TOOLS
    : ALL_TOOLS.filter(t => t.intent === activeIntent)

  const faqs = [
    {
      q: 'Is PDFNova really 100% free with unlimited usage?',
      a: 'Yes! PDFNova has zero paywalls, zero daily document limits, and no credit card requirements. You can merge, edit, compress, and convert as many PDF files as you need, completely free.'
    },
    {
      q: 'Do I need to sign up or create an account to use the tools?',
      a: 'No sign-up or registration is required. You can launch any tool, drop your files, make your edits, and download the finished documents immediately without entering an email or password.'
    },
    {
      q: 'Will PDFNova add watermarks to my edited or merged files?',
      a: 'Never. All outputs generated by PDFNova are 100% clean and watermark-free, making them suitable for official, academic, and business documents.'
    },
    {
      q: 'How does in-browser client-side privacy work?',
      a: 'Unlike traditional PDF websites that upload your confidential files to remote third-party cloud servers, PDFNova processes your files locally inside your browser using WebAssembly and modern web technologies. Your sensitive documents never leave your computer or phone.'
    },
    {
      q: 'Can I edit existing text word-by-word on scanned PDFs?',
      a: 'Yes! PDFNova features an advanced word-by-word text editor with built-in optical character recognition (OCR). It automatically identifies existing words and numbers on scanned exam papers, forms, and documents, allowing you to backspace, replace, or whiteout text seamlessly.'
    },
    {
      q: 'Can I compress a PDF to a specific file size in KB or MB?',
      a: 'Yes. With our PDF and image compression tools, you can pick extreme, high, or medium compression presets, or specify exact maximum dimensions and quality levels to meet strict upload size thresholds (such as 200 KB or 1 MB).'
    }
  ]

  return (
    <div className="space-y-16 pb-20 animate-fade-in">

      {/* ── HERO SECTION ── */}
      <section className="text-center pt-10 pb-6 max-w-4xl mx-auto px-4">
        {/* Top Floating Trust Pill */}
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-pill bg-success/10 text-success border border-success/25 text-xs font-semibold mb-6 shadow-sm">
          <span className="w-2 h-2 rounded-full bg-success animate-pulse" />
          <span>NO SIGN-UP REQUIRED • 100% FREE &amp; UNLIMITED • ZERO WATERMARKS</span>
        </div>

        <h1 className="font-display text-4xl sm:text-6xl font-extrabold text-text tracking-tight leading-[1.12] mb-5">
          The Free, Unlimited <span className="text-accent underline decoration-accent/30">PDF Suite</span> That Respects Your Privacy.
        </h1>

        <p className="text-base sm:text-xl text-text-secondary leading-relaxed max-w-2xl mx-auto mb-8 font-normal">
          Merge, edit text word-by-word, compress file size to exact KB/MB, sign, and convert documents directly inside your browser. No accounts, no paywalls, and your files never leave your device.
        </p>

        {/* 4 Core Value Badges */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 max-w-3xl mx-auto text-left mb-10">
          {TRUST_ITEMS.map((item, idx) => (
            <div
              key={idx}
              className="flex flex-col p-3 rounded-xl bg-surface border border-border shadow-sm hover:border-accent/40 transition-colors"
            >
              <div className="flex items-center gap-2 mb-1 text-accent">
                <Icon name={item.icon} size={16} />
                <span className="font-semibold text-xs text-text">{item.label}</span>
              </div>
              <span className="text-[11px] text-text-muted">{item.sub}</span>
            </div>
          ))}
        </div>

        {/* Primary Action Shortcuts */}
        <div className="flex flex-wrap items-center justify-center gap-3">
          <Link
            to="/tool/edit"
            className="px-5 py-2.5 rounded-pill text-sm font-semibold bg-accent text-white shadow-sm hover:bg-accent/90 transition-all flex items-center gap-2"
          >
            <span>✏️ Edit PDF Text Online</span>
          </Link>
          <Link
            to="/tool/merge"
            className="px-5 py-2.5 rounded-pill text-sm font-semibold bg-surface hover:bg-bg-alt text-text border border-border shadow-sm transition-all flex items-center gap-2"
          >
            <span>🔗 Merge Multiple PDFs</span>
          </Link>
          <Link
            to="/tool/compress"
            className="px-5 py-2.5 rounded-pill text-sm font-semibold bg-surface hover:bg-bg-alt text-text border border-border shadow-sm transition-all flex items-center gap-2"
          >
            <span>🗜 Compress PDF Size</span>
          </Link>
        </div>
      </section>

      {/* ── FILTER TABS BY INTENT ── */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center gap-2 overflow-x-auto pb-3 scrollbar-none border-b border-border">
          {INTENTS.map((intent) => {
            const isActive = activeIntent === intent
            const iconName = INTENT_ICONS[intent] || 'File'

            return (
              <button
                key={intent}
                onClick={() => setActiveIntent(intent)}
                className={`flex items-center gap-2 px-4 py-2 rounded-pill text-xs sm:text-sm font-medium transition-all whitespace-nowrap ${
                  isActive
                    ? 'bg-accent text-white shadow-sm font-semibold'
                    : 'bg-surface hover:bg-bg-alt text-text-secondary border border-border'
                }`}
              >
                <Icon name={iconName} size={15} />
                <span>{intent}</span>
              </button>
            )
          })}
        </div>
      </section>

      {/* ── TOOLS GRID ── */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 sm:gap-5">
          {displayedTools.map((tool) => (
            <Link
              key={tool.id}
              to={tool.route}
              className="group relative flex flex-col p-5 rounded-xl bg-surface hover:bg-surface-elevated border border-border hover:border-border-focus hover:shadow-md transition-all duration-200"
            >
              <div className="flex items-center justify-between mb-4">
                <div
                  className="w-10 h-10 rounded-lg flex items-center justify-center text-white shadow-sm group-hover:scale-105 transition-transform"
                  style={{ backgroundColor: tool.color }}
                >
                  <Icon name={tool.icon} size={20} />
                </div>

                {tool.badge && (
                  <span
                    className={`text-[10px] font-semibold px-2 py-0.5 rounded-pill uppercase tracking-wider ${
                      tool.badge === 'Popular'
                        ? 'bg-accent/15 text-accent-text border border-accent/20'
                        : tool.badge === 'Free'
                        ? 'bg-success/15 text-success border border-success/30'
                        : 'bg-bg-alt text-text-muted border border-border'
                    }`}
                  >
                    {tool.badge}
                  </span>
                )}
              </div>

              <h3 className="text-base font-semibold text-text group-hover:text-accent transition-colors flex items-center justify-between">
                <span>{tool.name}</span>
                <Icon
                  name="ArrowRight"
                  size={15}
                  className="opacity-0 -translate-x-1 group-hover:opacity-100 group-hover:translate-x-0 transition-all text-accent"
                />
              </h3>

              <p className="text-xs text-text-muted mt-1.5 leading-relaxed flex-1">
                {tool.desc}
              </p>

              <div className="mt-4 pt-3 border-t border-border/60 flex items-center justify-between text-[11px] text-text-muted font-medium">
                <span>{tool.intent}</span>
                <span className="text-accent group-hover:underline">Open tool →</span>
              </div>
            </Link>
          ))}
        </div>
      </section>

      {/* ── SEO SECTION 1: COMPARISON TABLE ── */}
      <section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pt-8">
        <div className="bg-surface border border-border rounded-2xl p-6 sm:p-8 shadow-sm">
          <div className="text-center max-w-2xl mx-auto mb-8">
            <h2 className="text-2xl sm:text-3xl font-bold text-text mb-3">
              Why PDFNova Ranks Above Traditional PDF Tools
            </h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              Most online PDF services force sign-ups, set 2-task daily limits, or upload your sensitive documents to distant cloud servers. PDFNova is engineered differently.
            </p>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs sm:text-sm">
              <thead>
                <tr className="border-b border-border text-text-muted">
                  <th className="py-3 px-4 font-semibold">Features</th>
                  <th className="py-3 px-4 font-bold text-accent">PDFNova</th>
                  <th className="py-3 px-4 font-normal">iLovePDF</th>
                  <th className="py-3 px-4 font-normal">Smallpdf</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/60 text-text">
                <tr>
                  <td className="py-3.5 px-4 font-medium">Account / Sign-Up Requirement</td>
                  <td className="py-3.5 px-4 text-success font-semibold">None (100% Instant)</td>
                  <td className="py-3.5 px-4 text-text-muted">Required for limits</td>
                  <td className="py-3.5 px-4 text-text-muted">Required</td>
                </tr>
                <tr>
                  <td className="py-3.5 px-4 font-medium">Watermark Policy</td>
                  <td className="py-3.5 px-4 text-success font-semibold">Zero Watermarks (Free)</td>
                  <td className="py-3.5 px-4 text-text-muted">Clean</td>
                  <td className="py-3.5 px-4 text-text-muted">Watermarks on some</td>
                </tr>
                <tr>
                  <td className="py-3.5 px-4 font-medium">File Security &amp; Privacy</td>
                  <td className="py-3.5 px-4 text-success font-semibold">100% In-Browser (Never Uploaded)</td>
                  <td className="py-3.5 px-4 text-text-muted">Uploaded to cloud</td>
                  <td className="py-3.5 px-4 text-text-muted">Uploaded to cloud</td>
                </tr>
                <tr>
                  <td className="py-3.5 px-4 font-medium">Word-by-Word Text Editing + OCR</td>
                  <td className="py-3.5 px-4 text-success font-semibold">Included Free</td>
                  <td className="py-3.5 px-4 text-text-muted">Paid Premium only</td>
                  <td className="py-3.5 px-4 text-text-muted">Paid Pro only</td>
                </tr>
                <tr>
                  <td className="py-3.5 px-4 font-medium">Daily Task Limits</td>
                  <td className="py-3.5 px-4 text-success font-semibold">Unlimited Free</td>
                  <td className="py-3.5 px-4 text-text-muted">Limited per day</td>
                  <td className="py-3.5 px-4 text-text-muted">1–2 tasks/day free</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* ── SEO SECTION 2: 3-STEP GUIDE ── */}
      <section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-10">
          <h2 className="text-2xl sm:text-3xl font-bold text-text mb-2">
            How to Work with PDFs in 3 Simple Steps
          </h2>
          <p className="text-xs sm:text-sm text-text-muted">
            Fast, intuitive workflow designed for students, legal teams, and businesses.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-6 rounded-xl bg-surface border border-border">
            <div className="w-9 h-9 rounded-full bg-accent/15 text-accent font-bold flex items-center justify-center text-sm mb-4">
              1
            </div>
            <h3 className="text-base font-semibold text-text mb-2">Select or Drop Your PDF</h3>
            <p className="text-xs text-text-secondary leading-relaxed">
              Choose any PDF, image, or document from your computer or phone. Files load immediately in memory without slow cloud uploads.
            </p>
          </div>

          <div className="p-6 rounded-xl bg-surface border border-border">
            <div className="w-9 h-9 rounded-full bg-accent/15 text-accent font-bold flex items-center justify-center text-sm mb-4">
              2
            </div>
            <h3 className="text-base font-semibold text-text mb-2">Merge, Edit or Compress</h3>
            <p className="text-xs text-text-secondary leading-relaxed">
              Rearrange pages, click words to replace text, apply signatures, erase unwanted sections, or reduce file sizes down to your target KB.
            </p>
          </div>

          <div className="p-6 rounded-xl bg-surface border border-border">
            <div className="w-9 h-9 rounded-full bg-accent/15 text-accent font-bold flex items-center justify-center text-sm mb-4">
              3
            </div>
            <h3 className="text-base font-semibold text-text mb-2">Download Instantly</h3>
            <p className="text-xs text-text-secondary leading-relaxed">
              Click download to get your high-resolution, watermark-free document. Your original document remains 100% confidential.
            </p>
          </div>
        </div>
      </section>

      {/* ── SEO SECTION 3: FAQ ACCORDION ── */}
      <section className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-6">
        <div className="text-center mb-8">
          <h2 className="text-2xl sm:text-3xl font-bold text-text mb-2">
            Frequently Asked Questions
          </h2>
          <p className="text-xs sm:text-sm text-text-muted">
            Everything you need to know about PDFNova's free tools and security.
          </p>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, index) => {
            const isOpen = openFaq === index
            return (
              <div
                key={index}
                className="rounded-xl border border-border bg-surface overflow-hidden transition-colors"
              >
                <button
                  onClick={() => setOpenFaq(isOpen ? null : index)}
                  className="w-full p-4 sm:p-5 text-left flex items-center justify-between gap-4 font-medium text-sm sm:text-base text-text hover:bg-bg-alt/50 transition-colors"
                >
                  <span>{faq.q}</span>
                  <span className="text-accent text-lg font-bold flex-shrink-0">
                    {isOpen ? '−' : '+'}
                  </span>
                </button>
                {isOpen && (
                  <div className="px-4 sm:px-5 pb-5 text-xs sm:text-sm text-text-secondary leading-relaxed border-t border-border/50 pt-3 bg-bg-alt/20">
                    {faq.a}
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </section>

    </div>
  )
}
